#normal estimation
float32 radius_search #radius of the sphere for the nearest neighbor search
int32 max_nn #max number of nearest neighbors to use for the feature estimation

#planar patch detection
float32 normal_variance_threshold_deg
float32 coplanarity_deg
float32 outlier_ratio
float32 min_plane_edge_length
int32 min_num_points
int32 search_nn

#ransac
float32 distance_threshold
int32 ransac_n
int32 num_iterations

---

Plane[] x_planes
Plane[] y_planes
Plane[] z_planes